### PR TITLE
print ruby version

### PR DESCRIPTION
**Pull request by steveoh**
## Description

refs #203
Print ruby version in container start up since jekyll does not do that.

### CODE REVIEW

**Comment by envygeeks** [comment]
If you're looking for it to be output when you run in Netflify, you'll probably want to put it in https://github.com/envygeeks/jekyll-docker/blob/master/repos/jekyll/copy/all/usr/jekyll/bin/jekyll because the `RUN` command is only output at build time and would only be seen on our Travis-CI builds, or if you build it yourself.

**Comment by steveoh** [comment]
I can pin the ruby version in netlify with a `.ruby-version` file. 

I was hoping it would show up in the docker log when I run `docker-compose up`

This is a sample of the log I see

```

**Comment by envygeeks** [comment]
Fair enough.

**Comment by envygeeks** [comment]
Thanks 💖

**Comment by steveoh** [comment]
If I pull the image tomorrow, will I be able to test this?

**Comment by envygeeks** [comment]
My build system is automatic, it was deployed when I merged it.

**Comment by steveoh** [comment]
So, then, I'm not sure I put that print statement in the right place or with the correct syntax. I pulled the latest image and started it up and it did not print the version. I'm not sure how to troubleshoot this and I don't want to take up too much of your time.

**Comment by envygeeks** [comment]
It's not going to print the version except on Travis-CI as noted.

**Comment by steveoh** [comment]
Ok, then I'm going to put it in the spot you mentioned earlier as well.

**Pull request merged**
