### PR TITLE
Changing README again

### PR DESCRIPTION
**Pull request by lupa18**
- [x ] This is a documentation change.

## Description

Sorry, but I continued doing experiments and realize that you can run docker-compose from a sub-folder of compose root's file folder, so I modify readme again. 

I hope be clearer this time. 

thanks in advance!

### CODE REVIEW

**Comment by envygeeks** [comment]
Can you please rebase? Thanks!

**Comment by lupa18** [comment]
Did I rebased correctly ?

**Comment by envygeeks** [comment]
Hey @lupa18 it looks like you might have created some competing commits that will ovewrite some changes, if you can get  this fixed this weekend I'll get this merged, sorry about not responding sooner,  busy month.

It looks the competing commits that would cause problems are merging of outdated stuff, I guess I did change master again yesterday, you could always `git rebase -i` those out, and then squash all your changes into a single commit for easy review too!

Thanks and sorry again for not responding faster.

**Comment by envygeeks** [comment]
Looks like this pull request was obsoleted by #222.  Thanks!

**Pull request closed without merging**
